### ISSUE TITLE
NLTHA notebook output file error

### ISSUE THREAD

**Issue by raoanirudh** [GEMScienceTools/rmtk#25]
The hard-coded output file path `'../../../../../../rmtk_data/output/fragility_output.csv'` on lines 928-929 of `utils.py` seems to be incorrect.

**Comment by ccasotto** [comment]
it seems to me that all the outputpath have been defined as input of the functions now, do you @raoanirudh agree?

**Comment by ccasotto** [comment]
The function referring to this issue is not used anywhere

**Comment by raoanirudh** [comment]
Then maybe we could safely delete it.
