### ISSUE TITLE
Plotting gmf notebook

### ISSUE THREAD

**Issue by CatalinaYepes** [GEMScienceTools/rmtk#39]
The rmtk should have the option for plotting gmf from scenario calculations.
Users could indicate if the map should be done for the mean (assigning zero), or for a given gmf (e.g to visualise spatial correlation).

**Comment by raoanirudh** [comment]
The plotting module of the rmtk has been deprecated. The functionality that was provided by this module is now available with the OQ-IRMT plugin for QGIS. eg: https://github.com/gem/oq-irmt-qgis/pull/181
