### ISSUE TITLE
MDOF-SDOF notebook

### ISSUE THREAD

**Issue by raoanirudh** [GEMScienceTools/rmtk#51]
It might be better to provide two notebooks, one based on the Eurocode and the other based on the FEMA-440, since they use similar terms like Γ to refer to different things.

**Comment by raoanirudh** [comment]
Damage models for interstory drift should be improved.

**Comment by raoanirudh** [comment]
Earlier comment by @ccasotto: A function should be built to convert not only the pushover curve, but also the corresponding limit states in terms of ISD, to be used in sdof system.

**Comment by raoanirudh** [comment]
### ATC 40

![atc40](https://cloud.githubusercontent.com/assets/1707414/10336166/0f0f94c0-6cf7-11e5-8e2d-c4388e63a0a7.png)

### Eurocode 8

<img width="671" alt="ec8" src="https://cloud.githubusercontent.com/assets/1707414/10336167/0f248df8-6cf7-11e5-8801-49071ad35930.png">

### FEMA 440

<img width="605" alt="fema440" src="https://cloud.githubusercontent.com/assets/1707414/10336168/0f2da334-6cf7-11e5-8706-62748766256a.png">

**Comment by ccasotto** [comment]
I would leave it for after the workshop, meanwhile we can keep the ATC40 method, which is the less approximated. Do you @raoanirudh and @VSilva  agree?

**Comment by raoanirudh** [comment]
### HAZUS

<img width="729" alt="1" src="https://cloud.githubusercontent.com/assets/1707414/18628307/e8a4156a-7e5f-11e6-8c69-d18c49a668bd.png">
<img width="720" alt="2" src="https://cloud.githubusercontent.com/assets/1707414/18628308/e8bfb05e-7e5f-11e6-97e7-700a2b760c09.png">
<img width="720" alt="3" src="https://cloud.githubusercontent.com/assets/1707414/18628309/e8c2016a-7e5f-11e6-8e98-8ea9c30524ad.png">

**Comment by raoanirudh** [comment]
Closed, because outdated.
