### ISSUE TITLE
Update RMTK structure figure

### ISSUE THREAD

**Issue by raoanirudh** [GEMScienceTools/rmtk#52]
The labels in the RMTK structure figure are misaligned. This appears to be browser dependent.
### On Firefox

<img width="840" alt="rmtk-structure-firefox" src="https://cloud.githubusercontent.com/assets/1707414/10336338/69a2d89c-6cf8-11e5-98c9-7e47f28f79b5.png">
### On Chrome

<img width="815" alt="rmtk-structure-chrome" src="https://cloud.githubusercontent.com/assets/1707414/10336339/69a3e94e-6cf8-11e5-9f63-3df2cbf9ccf5.png">

**Comment by raoanirudh** [comment]
@ccasotto and @mabevillar 's new modules should also be added to this figure.

**Comment by ccasotto** [comment]
My module has been added as a branch of Nonlinear Time History Analysis, therefore it is not needed to include it in the main figure

**Comment by raoanirudh** [comment]
Closed, because outdated.
